apiVersion: v1
kind: Service
metadata:
  name: dellpoc-service
  namespace: dellpoc
spec:
  type: NodePort
  selector:
    app: dellpoc
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
